### ISSUE TITLE
Console warning cannot update during an existing state transition

### ISSUE THREAD

**Issue by jeffvg** [pxblue/angular-component-library#103]
#### Describe the bug
On initial load warning displays path=/story/intro-overview--px-blue-angular-components

Render methods should be a pure function of props and state.
in Unknown (created by Context.Consumer)
    in WithTheme(Component)
    in WithTheme(Component) (created by Preview)
    in div (created by Context.Consumer)
    in Side (created by FlexBar)
    in div (created by Context.Consumer)
    in Styled(div) (created by FlexBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in div (created by SimpleBar)
    in SimpleBar
    in Unknown (created by Context.Consumer)
    in Styled(Component) (created by ScrollArea)
    in ScrollArea
    in Unknown (created by Context.Consumer)
    in Bar (created by FlexBar)
    in div (created by FlexBar)
    in FlexBar
    in Unknown (created by Context.Consumer)
    in Styled(Component) (created by Preview)
    in Provider (created by Preview)
    in Preview (created by Context.Consumer)
    in ManagerConsumer....
   

#### What is the expected behavior?
no warning
#### What are the steps to reproduce?
1. Run angular storybook
2. Dev tools

#### What is your environment?

 Framework
- [ ] Angular
- [ ] React
- [ ] Ionic
- [ ] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [X] Chrome
- [X] Firefox

 Operating System
- [ ] MacOS
- [X] Windows
- [ ] Other
		
#### Anything else to add?
![ng-storybook](https://user-images.githubusercontent.com/37150565/86142563-51ad7c80-bac1-11ea-9f2f-a068e00fdcd2.png)

**Comment by joebochill** [comment]
This appears to be an upstream bug in the @storybook-addons plugin (storybookjs/storybook#10204). Disabling the plugin makes the error go away, so that's one way we could fix it but we would lose the viewport dropdown picker (not sure how valuable that is). It also appears to be resolved in storybook 6.

**Comment by emclaug2** [comment]
I'm re-adding the `wont-fix` issue on this because we shouldn't spend time maintaining storybook5 if we ever plan on upgrading to 6+.

**Comment by emclaug2** [comment]
Closing this because we won't fix it.
