### ISSUE TITLE
Ionic Support for Drawer Component

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#110]
#### Describe the desired behavior
DrawerHeader text should not be inside of the Safe Area.   Instead, the DrawerHeader should have the top padded.
DrawerHeader height should match app bar's height when appearing inside of an ionic app. 

#### Describe the current behavior
The header text overlaps with the content of the safe area and the DrawerHeader toolbar height does not match the app-bar's 
height.
<img width="481" alt="Screen Shot 2020-07-13 at 10 25 12 AM" src="https://user-images.githubusercontent.com/6538289/87319244-5d546680-c4f7-11ea-89b4-9d978d708805.png">

#### Is this request related to a current issue?
No

**Comment by huayunh** [comment]
TODO: @emclaug2 update the image

**Comment by emclaug2** [comment]
This was something that was fixed in the pxb-cli, the .mat-toolbar needed some adjusted styles added to it.  I think this can be closed.

**Comment by huayunh** [comment]
@emclaug2 look at this and see if we need a high priority tag here

**Comment by emclaug2** [comment]
The drawer in ionic needs styles on the `mat-toolbar` to work; putting these styles in this component will not fix the issue.  The styles needed are supposed to be put in the global styles of an ionic app, which our pxb cli now does. 

I'm closing this issue.
