### ISSUE TITLE
UserMenuAvatar Component

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#117]
#### Describe the desired behavior
Create an Avatar component that can be used by end-users.

#### Describe the current behavior
UserMenuAvatar is a component bundled to the UserMenu component, not advertised as a standalone component.

#### Is this request related to a current issue?
No

#### Additional Context
Angular material has a mat-card-avatar directive that may be an alternative to explore.

**Comment by jeffvg** [comment]
moved to PXBLUE-1921
