### ISSUE TITLE
angular-component-library builds with warnings

### ISSUE THREAD

**Issue by daileytj** [pxblue/angular-component-library#130]
#### Describe the bug
Building the angular-component-library throws multiple warnings.

#### What is the expected behavior?
The component library should build without warnings

#### What are the steps to reproduce?
1. Clone angular-component-library repo
2. Run ```yarn build```

#### Screenshots or links to minimum reproduction example
Compiling TypeScript sources through ngc
Bundling to FESM2015
WARNING: 'ElementRef' is imported from external module '@angular/core' but never used
WARNING: 'MatMenuTrigger' is imported from external module '@angular/material/menu' but never used
Bundling to FESM5
WARNING: 'ElementRef' is imported from external module '@angular/core' but never used
WARNING: 'MatMenuTrigger' is imported from external module '@angular/material/menu' but never used
Bundling to UMD
WARNING: 'tslib' is imported by ../dist/fesm5/pxblue-angular-components.js, but could not be resolved – treating it as an external dependency

**Comment by emclaug2** [comment]
This will go away (99% sure) when we update to angular 9+.

**Comment by emclaug2** [comment]
New warnings in Ng10

Compiling TypeScript sources through ngc
Bundling to FESM2015
WARNING: 'ElementRef' is imported from external module '@angular/core' but never used
WARNING: 'MatMenuTrigger' is imported from external module '@angular/material/menu' but never used
Bundling to UMD
WARNING: 'tslib' is imported by ../dist/esm2015/core/drawer/drawer.component.js, but could not be resolved – treating it as an external dependency
WARNING: 'tslib' is imported by ../dist/esm2015/core/drawer/drawer-body/drawer-body.component.js, but could not be resolved – treating it as an external dependency
WARNING: 'tslib' is imported by ../dist/esm2015/core/drawer/drawer-footer/drawer-footer.component.js, but could not be resolved – treating it as an external dependency
WARNING: 'tslib' is imported by ../dist/esm2015/core/drawer/drawer-header/drawer-header.component.js, but could not be resolved – treating it as an external dependency
WARNING: 'tslib' is imported by ../dist/esm2015/core/drawer/drawer-layout/drawer-layout.component.js, but could not be resolved – treating it as an external dependency
WARNING: 'tslib' is imported by ../dist/esm2015/core/drawer/drawer-subheader/drawer-subheader.component.js, but could not be resolved – treating it as an external dependency
WARNING: 'tslib' is imported by ../dist/esm2015/core/drawer/drawer-body/nav-group/drawer-nav-group.component.js, but could not be resolved – treating it as an external dependency
WARNING: 'tslib' is imported by ../dist/esm2015/core/drawer/drawer-body/nav-item/drawer-nav-item.component.js, but could not be resolved – treating it as an external dependency
Minifying UMD bundle
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Removing prettier section in package.json.
Removing devDependencies section in package.json.
Built @pxblue/angular-components

**Comment by emclaug2** [comment]
Closing this due to migrating over to ng11 in TBD.
