### ISSUE TITLE
Empty State Icon/Title Padding 

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#152]
#### Describe the bug
The space between the title and icon doesn't match against React's empty state.

#### What is the expected behavior?
They should look the exact same.

#### Screenshots or links to minimum reproduction example

React is only left, Angular on right:

<img width="1086" alt="Screen Shot 2020-09-03 at 1 16 00 PM" src="https://user-images.githubusercontent.com/6538289/92146546-e1381a00-ede7-11ea-8dd4-39484f926879.png">

**Comment by huayunh** [comment]
Go with React's padding

**Comment by huayunh** [comment]
Stolen from Joe's unpublished design spec:

![image](https://user-images.githubusercontent.com/8997218/92263711-10638f80-eeab-11ea-8005-ac816c8c2245.png)
