### ISSUE TITLE
Remove icon flipping for icons with no directionalities in showcase & storybook

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-component-library#155]
#### Describe the bug

Some icons should not be flipped in showcase & storybook

#### What is the expected behavior?

The flipping logic has been removed from the components in #154 

should double-check showcase & storybook; adhere to [material's bidirectionality guideline](https://material.io/design/usability/bidirectionality.html#mirroring-elements)

**Comment by joebochill** [comment]
@daileytj  said that he went through and audited these a week or so ago and there were still issues with some icons being flipped automatically that shouldn't be and some icons that should be that were not flipped.

We need to go through and identify where the issues are in the component library (should have no flipping logic except for icons that are used internally) and in the demos (icons that are passed in through ng-content need to be flipped by the end-user where appropriate).

**Comment by emclaug2** [comment]
Showcase still needs to have the icons flipped correctly; storybook is complete now.
