### ISSUE TITLE
Drawer nest background color doesn't match react

### ISSUE THREAD

**Issue by joebochill** [pxblue/angular-component-library#158]
#### Describe the bug
Angular is using gray[50] for the nested item background color, React is using white[200]. 

#### What is the expected behavior?
They should match. I'm inclined to not use gray[50] since that is the default application background color and we don't want them to blend into each other.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/92945608-832cb780-f423-11ea-9311-1c905cdadb8a.png)

**Comment by huayunh** [comment]
Is this a theme thing or a component lib thing?

**Comment by emclaug2** [comment]
This is a theme-related issue.  I'm going to relocate this issue into the themes repo if still needed.

**Comment by emclaug2** [comment]
Closing this issue since Angular is already using white[200] for nested nav item bg color.

https://pxblue-components.github.io/angular-dev/?path=/story/components-drawer--with-nested-nav-items
