### ISSUE TITLE
Icons used in hero bleed past background

### ISSUE THREAD

**Issue by jeffvg** [pxblue/angular-component-library#166]
#### Describe the bug
Currently the PX Blue barley svg icon bleeds beyond the hero background
#### What is the expected behavior?
icons to adjust to size of supported hero sizes

#### What are the steps to reproduce?
1. Go to https://pxblue-components.github.io/angular-dev/?path=/story/components-hero--with-icon-sizes-and-types

#### Screenshots or links to minimum reproduction example

![image](https://user-images.githubusercontent.com/37150565/89929305-12517000-dbd7-11ea-9e3d-bec72b858557.png)

**Comment by huayunh** [comment]
Why moving the issue?

**Comment by emclaug2** [comment]
The Hero API needs some attention.  

Maybe refactor the Hero accept an icon that is already the desired size, instead of a `iconSize` prop that will scale the icon.  

The backgroundColor can be a fixed padding wrapper element around the icon that is provided.

**Comment by jeffvg** [comment]
moved to PXBLUE-1922
