### ISSUE TITLE
Stackblitz Angular 10 Showcase Icon Issue

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#184]
#### Describe the bug.
Angular 10 Stackblitz not loading icons

#### What is the expected behavior?
Stackblitz loads icons in the demo project without error.

#### What are the steps to reproduce?
https://stackblitz.com/github/pxblue/angular-showcase-demo/tree/dev

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/95332624-b410d880-0879-11eb-979f-95f1b4aef6f2.png)

**Comment by huayunh** [comment]
Should be fix; @emclaug2 to check

**Comment by emclaug2** [comment]
This issue is resolved. 

View here: https://stackblitz.com/github/pxblue/angular-showcase-demo/tree/dev
