### ISSUE TITLE
Dot-Stepper Component

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#190]
#### Describe the desired behavior
Create a dot-stepper component that we can distribute to teams.

#### Describe the current behavior
We have a dot-stepper component already made in the angular-workflows repo, but it is not component-tized yet. 

#### Is this request related to a current issue?
No

#### Additional Context

![image](https://user-images.githubusercontent.com/6538289/97183262-f2f8c680-1773-11eb-9101-ae2f69f7130d.png)

**Comment by huayunh** [comment]
This is in the backlog

**Comment by emclaug2** [comment]
Ah okay, I'm going to close this due to duplicated items.
