### ISSUE TITLE
Incorrect shadow applied on Drawer

### ISSUE THREAD

**Issue by joebochill** [pxblue/angular-component-library#202]
#### Describe the bug
The shadow on the Drawer component does not match the design in Figma. We have a single box shadow defined currently: 

#### What is the expected behavior?
Component should be using the styles for 4dp shadow (elevation = 4). These should be coming from the mat-elevation class or mixin, which includes a blend of box shadows

#### What are the steps to reproduce?
1. Go to...
2. Click on...

#### Screenshots or links to minimum reproduction example
Current definition:
![image](https://user-images.githubusercontent.com/29152776/103773878-ba8a2a00-4ff9-11eb-9184-7399e7ff27f2.png)

Should look more like:
![image](https://user-images.githubusercontent.com/29152776/103773922-c83faf80-4ff9-11eb-9323-d73594281566.png)
but with the correct black[500] color.

Currently:
![image](https://user-images.githubusercontent.com/29152776/103774011-e9a09b80-4ff9-11eb-9105-1cf49e5139bb.png)

Should look like:
![image](https://user-images.githubusercontent.com/29152776/103774054-f91fe480-4ff9-11eb-83a9-dfec2d6dc418.png)

		
#### Anything else to add?
This is probably something that needs to be adjusted in the component library and the theme (to get the right colors).

**Comment by emclaug2** [comment]
#210 fixes this.
