### ISSUE TITLE
Update dependencies & peer dependencies

### ISSUE THREAD

**Issue by joebochill** [pxblue/angular-component-library#242]
#### Describe the desired behavior
Check the current/latest version of all dependencies and peer dependencies. Update the package.json to include the latest.

#### Describe the current behavior
Using old versions of dependencies.

#### Is this request related to a current issue?
The newest version of NPM fails on npm install when there are peer dependency issues. 

#### Additional Context
After updating the versions of dependencies, make sure that things still work as expected.

**Comment by joebochill** [comment]
I think we only updated the PX Blue dependencies, but there are other dependencies that are still out of date

**Comment by emclaug2** [comment]
This needs to be applied to the new major version branch.

**Comment by emclaug2** [comment]
This should be addressed now for the release branch of the component library; the showcase demo has a separate PR to update the dependencies, but this should happen after the v5.0.0 of our components package is published so we can update all the deps at once.
