### ISSUE TITLE
Info List Item with PX Blue icon appears to be off-centered

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-component-library#252]
PX Blue icons in info list items should be properly vertically centered.

#### What are the steps to reproduce?
1. Go to https://pxblue-components.github.io/angular-dev/?path=/story/components-info-list-item--within-a-full-list

#### Screenshots or links to minimum reproduction example

![image](https://user-images.githubusercontent.com/8997218/113818915-859b8980-9746-11eb-86dd-c7a45eb84e60.png)

#### Environment
MacOS Chrome
		
#### Anything else to add?
I think we tried attacking this issue before, and there were some problems with the use of icon fonts. Feel free to close this issue if we've tried fixing it and found this to be an external dependency issue.

**Comment by joebochill** [comment]
Might be related to the icon wrapper height being incorrect. The icon inside of the wrapper is overflowing that wrapper container.
