### ISSUE TITLE
Remove InfoListItem icon color inline style from story

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#259]
#### Describe the desired behavior
This story has an inline style for the color.
https://pxblue-components.github.io/angular/?path=/story/components-info-list-item--with-icon

#### Describe the current behavior
Color should be set by the theme.

#### Is this request related to a current issue?
No

**Comment by joebochill** [comment]
This is another instance of a hardcoded color value being supplied inline. Removing that should clear this up and inherit the correct color based on the theme.
