### ISSUE TITLE
InfoListItem wrap prop doesn't break word

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#269]
#### Describe the bug
If I have a subtitle that is 1 long string and it needs to wrap, it won't.

#### What is the expected behavior?
`wrapTitle` and `wrapSubtitle` should wrap all

#### What are the steps to reproduce?
1. Go to storybook, `with full config` story
2. Make the subtitle one long word, try to cause an overflow. 

#### Environment

Chrome Windows

**Comment by huayunh** [comment]
You mean to apply hyphens:auto when wrapTitle and wrapSubtitle are on?

**Comment by emclaug2** [comment]
> You mean to apply hyphens:auto when wrapTitle and wrapSubtitle are on?

I was thinking more of a `word-break`: `break-all`.  Adding hyphens could make the data harder to read/copy-paste in some situations.  By default I'd like a break-all, but maybe it would be consider a break variant?

Instead of `wrapSubtitle` it could be `wrapSubtitleVariant`: `none` | `hyphen` | `all`. 

This could be a little confusing for users maybe?

**Comment by huayunh** [comment]
Same for React and maybe React Native.

**Comment by daileytj** [comment]
RN InfoListItem does not have a wrapTitle or wrapSubtitle prop so this doesn't currently apply.

**Comment by huayunh** [comment]
Whoever looks at this should log an issue in React too

**Comment by doctorbebo** [comment]
Working on this with @daileytj
