### ISSUE TITLE
Drawer Body does not hide browser tab on Mobile devices

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#272]
#### Describe the bug
Browser tab doesn't transition away on scroll down. 

#### What is the expected behavior?
Whenever scrolling down a web app on ios, the mobile tab should transition away and the Drawer body content should expand to be full screen; this doesn't happen on mobile. 

#### What are the steps to reproduce?
1. Open this app on mobile iphone and scroll down; observe browser tab doesn't transition away.
https://pxb-angular-theme-demo.web.app/dashboard

#### Environment

Safari, IOS

**Comment by huayunh** [comment]
Interesting... might be related to the `height:100%` css rule

**Comment by huayunh** [comment]
Window has to be the thing that scrolls, not the body content div

**Comment by huayunh** [comment]
PXBLUE-2158
