### ISSUE TITLE
Explain ILI's "wrapXXX" properties better

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-component-library#313]
#### Describe the desired behavior

Alter Info List Item's API table to make all the "wrap xxx" directives more explanatory

#### Describe the current behavior

Someone got confused over the verb "wrap" — is it a text-wrap, or is it like a wrapper around the `title`?

#### Additional Context

From green motion folks, whose native language is not English.

**Comment by emclaug2** [comment]
Fixed in #316
