### ISSUE TITLE
Stepper dots not centered when buttons are at different size

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-component-library#332]
#### Describe the bug

The dots part of `<pxb-mobile-stepper>` would be off-centered if a button is wider than another.

#### What is the expected behavior?

It should not use flexbox to style this.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/8997218/132382475-50afaa4d-44f7-4c80-a39d-c7456547a1cb.png)

#### Anything else to add?
This was discovered when I was wondering if we can add a skip button to the right.

**Comment by jeffvg** [comment]
lets try to fix this for this release

**Comment by emclaug2** [comment]
Fixed in #333
