### ISSUE TITLE
Enhance Subtitle Array in InfoListItem

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#37]
#### Describe the desired behavior
Current subtitle array only works with strings.

#### Describe the current behavior
Allow a user to pass in more than just a string array[].
Maybe also expand the [title] and [subtitle] to accept <ng-content>.

#### Is this request related to a current issue?
No

#### Additional Context
No

**Comment by andrupu** [comment]
Should we let subtitle accept ng-content?

**Comment by emclaug2** [comment]
Closing due to #52
