### ISSUE TITLE
Hero component not using pxblue theme 

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-component-library#4]
#### Describe the bug
The theme demo in @pxblue/theme is currently rendered with low text-background contrast: 
![image](https://user-images.githubusercontent.com/8997218/74690065-a3f19f00-51ab-11ea-8897-02b2597ed0b1.png)
Because [hero.component.scss](https://github.com/pxblue/angular-component-library/blob/master/components/src/core/hero/hero.component.scss) use local css to override the wrapper font color as `map-get($pxb-gray, 500);`.

#### What is the expected behavior?
Here's what it looks like in the react component library demo: 
![image](https://user-images.githubusercontent.com/8997218/74690205-24b09b00-51ac-11ea-98bb-255f0a530d91.png)
![image](https://user-images.githubusercontent.com/8997218/74690242-54f83980-51ac-11ea-9257-47724e4e830f.png)
Angular and React should match

#### What are the steps to reproduce?
1. Go to [Stackblitz demo](https://stackblitz.com/github/pxblue/themes/tree/master/angular/demo)
2. Toggle the dark theme on.

#### Screenshots or links to minimum reproduction example
Already provided as above.

#### What is your environment?
 Framework
- [x] Angular
- [ ] React
- [ ] Ionic
- [ ] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [x] Chrome
- [ ] Firefox

 Operating System
- [x] MacOS
- [ ] Windows
- [ ] Other

**Comment by emclaug2** [comment]
Our theme is defined in a separate repo; Hero component now supports light and dark themes.
