### ISSUE TITLE
ChannelValue not taking :host styles

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-component-library#44]
#### Describe the bug
In channel-value/channel-value.component.scss there is this field
```
:host {
    display: inline-flex;
    align-items: center;
}
```
but this style applied neither on storybook nor on showcase. 

#### What is the expected behavior?
Styles should go through so that the component `pxb-channel-value` can be properly vertically aligned in an info list item. This is also what React Component Library did in ChannelValue's React Counter Part. 

#### What are the steps to reproduce?
1. Go to showcase
2. See the list of info list items

#### Screenshots or links to minimum reproduction example
In showcase,
![image](https://user-images.githubusercontent.com/8997218/79584432-5e166180-809c-11ea-942b-6778b1c1da33.png)

#### What is your environment?

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [x] Chrome
- [ ] Firefox

 Operating System
- [x] MacOS
- [ ] Windows
- [ ] Other

**Comment by joebochill** [comment]
This happened when we switched to view encapsulation of none. We need to go through the components and see which ones were using :host styles before and do a little refactoring to remove the need for these rules (try to move the styles elsewhere).
