### ISSUE TITLE
Ripple Not Disabled on NavItem

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#468]
#### Describe the bug
Ripple effect is still present when clicking on a <blui-drawer-nav-item> even when the `ripple` input is set to false.

#### What is the expected behavior?
When `ripple` is set to false, the Material ripple effect should not be seen when clicking on the <blui-drawer-nav-item>.

#### What are the steps to reproduce?

1. Configure a <blui-drawer-nav-item> with the `ripple` property set to false
2. Observe that clicking on the nav item still shows the ripple effect.

#### Screenshots or links to minimum reproduction example
https://user-images.githubusercontent.com/8997218/182656913-896bdc15-7376-4371-82ac-a088f6f9657e.mov

#### Anything else to add?
You can test out this component in our documentation playground:

1. clone the repository
2. `yarn && yarn start`
3. navigate to http://localhost:4200/components/drawer/footer/playground

**Comment by ektasawant** [comment]
Screen recording for reproducing bug is here [recording](url)
