### ISSUE TITLE
API WordSmithing

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-component-library#55]
#### Describe the desired behavior
Update the Angular documentation to have a more angular-specific verbiage. 

#### Describe the current behavior
The current docs are a little confusing to understand, they can be edited a bit. 

#### Is this request related to a current issue?
No

#### Additional Context
Each API section in the components documentation is split into two parts:
1. The Inputs section
2. The ng-content section.

Each section has a small sentence that describes the section.
1. Inputs description
2. Ng-Content description.

### Proposal: 

**Inputs Description**
Verbiage: 
`<pxb-[component-name]` @Input properties: 

**Inputs Section:**
Change `Attributes` to ``@Input`.

**Ng-Content Description**
Verbiage: 
The following is projected into `<pxb-[component-name`>: 

**Ng-Content Section:**
Change `Attributes` to `Selector`.

**Comment by emclaug2** [comment]
The verbiage is up to discussion, I just threw something together.

**Comment by huayunh** [comment]
I 100% agree with the @input part. 

Judging from Angular Material, the "selector" thing seems to follow the following rules: 
If the directive [`MatListItem`](https://material.angular.io/components/list/api#MatListItem) has these selectors: `mat-list-item` `a[mat-list-item]` `button[mat-list-item]`, then `<mat-list-item>`, `<a mat-list-item>` and `<button mat-list-item>` will all get picked up as a `MatListItem`.

Under that rule, our Empty State API will become
| Selector    | Description                    | Required | Default |
| ----------- | ------------------------------ | -------- | ------- |
| [actions]   | action elements below the text | no       |         |
| [emptyIcon] | The large icon to display      | yes      |         |

**Comment by joebochill** [comment]
I like this...makes sense to me.

**Comment by emclaug2** [comment]
This will make sense until we start having components that support custom events, which will have @Outputs.  I think when that happens maybe we just have another API section.  Inputs, Outputs, and Classes would each have their own little table.

**Comment by emclaug2** [comment]
This was already addressed by @huayunh.  Closing this issue.
